### ISSUE TITLE
Add New Sponsor Logos [BATCH 1]

### ISSUE THREAD

**Issue by grant** [dubhacks/15f#8]

**Comment by mahirk** [comment]
@grant do we still need this?

**Comment by grant** [comment]
Yup. We should add all of our current sponsors.

**Comment by mahirk** [comment]
- [ ] IBM
- [ ] Concur
- [ ] Algorithmia
- [ ] Qumulo
- [ ] .co
- [ ] Zillow

**Comment by grant** [comment]
We should probably do this soonish
